const CARD_CONST = {
    0: {
        id: 0,
        name: "cannon - owl",
        image: {
            A: "textures/card/miniature_tower_cannon_3.png",
            B: "textures/card/miniature_tower_cannon_2.png",
            C: "textures/card/miniature_tower_cannon_1.png",
        },
        background: "textures/card/card_background_2.png",
        cardImage: "textures/card/card_tower_cannon.png",
        energy: 8,
    },
    1: {
        id: 1,
        name: "wizard - crow",
        image: {
            A: "textures/card/miniature_tower_wizard_3.png",
            B: "textures/card/miniature_tower_wizard_2.png",
            C: "textures/card/miniature_tower_wizard_1.png",
        },
        background: "textures/card/card_background_2.png",
        cardImage: "textures/card/card_tower_wizard.png",
        energy: 12,
    },
    2: {
        id: 2,
        name: "boomerang - frog",
        image: {
            A: "textures/card/miniature_tower_boomerang_3.png",
            B: "textures/card/miniature_tower_boomerang_2.png",
            C: "textures/card/miniature_tower_boomerang_1.png",
        },
        background: "textures/card/card_background_3.png",
        cardImage: "textures/card/card_tower_boomerang.png",
        energy: 10,
    },
    3: {
        id: 3,
        name: "oilGun - bunny",
        image: {
            A: "textures/card/miniature_tower_oil_gun_3.png",
            B: "textures/card/miniature_tower_oil_gun_2.png",
            C: "textures/card/miniature_tower_oil_gun_1.png",
        },
        background: "textures/card/card_background_2.png",
        cardImage: 'textures/card/card_tower_oil_gun.png',
        energy: 12,
    },
    4: {
        id: 4,
        name: "iceGun - polarBear",
        image: {
            A: "textures/card/miniature_tower_ice_gun_3.png",
            B: "textures/card/miniature_tower_ice_gun_2.png",
            C: "textures/card/miniature_tower_ice_gun_1.png",
        },
        background: "textures/card/card_background_2.png",
        cardImage: 'textures/card/card_tower_ice_gun.png',
        energy: 10,
    },
    5: {
        id: 5,
        name: "damage - goat",
        image: {
            A: "textures/card/miniature_tower_damage_3.png",
            B: "textures/card/miniature_tower_damage_2.png",
            C: "textures/card/miniature_tower_damage_1.png",
        },
        background: "textures/card/card_background_4.png",
        cardImage: 'textures/card/card_tower_damage.png',
        energy: 12,
    },
    6: {
        id: 6,
        name: "attackSpeed - snake",
        image: {
            A: "textures/card/miniature_tower_attack_speed_3.png",
            B: "textures/card/miniature_tower_attack_speed_2.png",
            C: "textures/card/miniature_tower_attack_speed_1.png",
        },
        background: "textures/card/card_background_1.png",
        cardImage: 'textures/card/card_tower_attack_speed.png',
        energy: 12,
    },
    7: {
        id: 7,
        name: "fireball",
        image: {
            A: "textures/card/card_potion_fireball.png",
            B: "textures/card/card_potion_fireball.png",
            C: "textures/card/card_potion_fireball.png",
        },
        background: "textures/card/card_background_2.png",
        cardImage: "textures/card/card_potion_fireball.png",
        energy: 8,
    },
    8: {
        id: 8,
        name: "frozen",
        image: {
            A: "textures/card/card_potion_frozen.png",
            B: "textures/card/card_potion_frozen.png",
            C: "textures/card/card_potion_frozen.png",
        },
        background: "textures/card/card_background_4.png",
        cardImage: "textures/card/card_potion_frozen.png",
        energy: 8,
    },
    9: {
        id: 9,
        name: "trap",
        image: {
            A: "textures/card/card_potion_trap.png",
            B: "textures/card/card_potion_trap.png",
            C: "textures/card/card_potion_trap.png",
        },
        background: "textures/card/card_background_1.png",
        cardImage: "textures/card/card_potion_trap.png",
        energy: 10,
    }
}